Use SSL URL for CH git repository.
Not sure why this was broken, but we were seeing:

error: RPC failed; result=22, HTTP code = 400

Whenever we tried to fetch from the repo.  Switching to an https://
repository URL fixed this.  I switched the deploy script and manually
updated the cached copy on staging.